.TH crystal 6 "24 May 2003" "Crystal" "Crystal"
.SH NAME
crystal -\ mud client
.SH SYNPOSIS
.B crystal
[-n] [-s] host [port]
.PP
.B crystal
[-n] telnet://host[:port]/
.PP
.B crystal
[-n] telnets://host[:port]/
.SH DESCRIPTION
.B crystal
is a fuss-free mud client with an interface similar to telnet.  It should
support all muds.  It has support for many ANSI codes, prompt grabbing,
window size negotiation, terminal type identification, the MCCP (mud compression) 
protocol, and TLS encryption (activated by 'telnets' in the URL or the -s option).
.PP
It has full line editing, similar to that available in bash/readline.
You can use page-up and page-down to scroll back and forward within the buffer
of all recieved text from the mud.
.PP
If you want it to never echo inputted text into the scrollback, use -n. This
can be configured at runtime with the 'set' command.
.PP
Within crystal, use control-] to get to the command-mode, and then 'help'
for a list of commands.
.SH AUTHORS
Written by Abi Brady <morwen@evilmagic.org>. Copyright (c) 2002-2025.
